<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="JITUMANI" failures="3" tests="5" name="Test" time="16.419" errors="0" timestamp="2024-09-24T23:55:14 IST">
  <testcase classname="testCases.TC003_LoginDataDrivenTest" name="verify_loginDDT" time="2.503"/>
  <testcase classname="testCases.TC003_LoginDataDrivenTest" name="verify_loginDDT" time="2.043">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TC003_LoginDataDrivenTest.verify_loginDDT(TC003_LoginDataDrivenTest.java:45)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- verify_loginDDT -->
  <testcase classname="testCases.TC003_LoginDataDrivenTest" name="verify_loginDDT" time="1.83">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TC003_LoginDataDrivenTest.verify_loginDDT(TC003_LoginDataDrivenTest.java:45)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- verify_loginDDT -->
  <testcase classname="testCases.TC003_LoginDataDrivenTest" name="verify_loginDDT" time="1.933">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TC003_LoginDataDrivenTest.verify_loginDDT(TC003_LoginDataDrivenTest.java:45)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- verify_loginDDT -->
  <testcase classname="testCases.TC003_LoginDataDrivenTest" name="verify_loginDDT" time="1.832"/>
</testsuite> <!-- Test -->
